version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - mern
    environment:
      MONGO_URL: mongodb://mongodb:27017/developer
    depends_on:
      - mongodb

  frontend:
    build: ./frontend  # ✅ this matches your folder
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - mern
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo_data:/data/db

networks:
  mern:
    driver: bridge

volumes:
  mongo_data:
